name: ML Image Detector CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Docker build
        run: |
          docker build -t image-detector .

      - name: Docker Run
        run: |
          docker run -d -p 5000:5000 --name test-container image-detector

      - name: Wait for Flask App to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:5000 && break
            echo "Waiting for Flask app..."
            sleep 3
          done

      - name: Download Sample Image
        run: |
          mkdir -p data
          curl -o data/sample.jpg https://raw.githubusercontent.com/keras-team/keras/main/docs/img/keras-logo-small.jpg

      - name: Run Tests
        run: |
          python test_app.py

      - name: Print Container Logs (on failure)
        if: failure()
        run: docker logs test-container

      - name: Cleanup
        run: docker rm -f test-container
